### ISSUE TITLE
Bug : Single Quotation in OAS schema fields my cause undesirable behaviors in generated code

### ISSUE THREAD

**Issue by katsujukou** [oqtopus-team/oqtopus-cloud#205]
### Describe the bug

When the OAS schema includes a single quote in fields related to machine-generated code, such as:

```yaml
    devices.DeviceDataUpdateResponse:
      type: object
      properties:
        message:
          type: string
          nullable: false
          default: Device's data updated        # Problem!
          example: Device's data updated
      required
``` 

the generated code contains a poorly escaped single-quoted string, which causes a syntax error:

```python
    def __init__(self, message='Device's data updated'):  # noqa: E501
        """DevicesDeviceDataUpdateResponse - a model defined in Swagger"""  # noqa: E501
        self._message = None
        self.discriminator = None
        self.message = message
```

Strictly speaking, this is not a bug in the `oqtopus-cloud` codebase, but it seems we should avoid using single quotes in this way in the schema to prevent such issues.

### Environment

None
